[package]

name = "crap_elgamal"
version = "0.0.1"
authors = ["Corey Richardson <corey@octayn.net>"]

[dependencies.rust-gmp]
git = "https://github.com/cmr/rust-gmp"
branch = "crypto"

[dependencies]
docopt = "*"
rustc-serialize = "*"

[[bin]]
name = "de-eg"
path = "src/de-eg.rs"
